name: Mobile Automation CI

on:
  push:
   branches:
    - main  # Or use the branch you're working with
  pull_request:

jobs:
  build:
   runs-on: macos-latest  # Use macOS for iOS, Ubuntu for Android or cross-platform

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Node.js
     uses: actions/setup-node@v3
     with:
      node-version: 'node'

   - name: Install dependencies
     run: |
      npm install
      npm install --save-dev @wdio/cli @wdio/appium-service appium allure-commandline

   - name: Install Appium
     run: npm install -g appium

   - name: Set up Android SDK
     uses: reactivecircus/android-emulator-runner@v2
     with:
          api-level: 30
          target: default
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-window -no-audio
          script: |
            adb devices
            appium &  # Start Appium server in the background
            sleep 10  # Wait for server to stabilize

   - name: Run Mobile Test
     run: |
      npm run android  # Runs android tests

   - name: Upload Allure Report as an Artifact
     uses: actions/upload-artifact@v4
     with:
      name: allure-report
      path: allure-report
