name: Mobile Automation CI

on:
  push:
    branches:
      - main  # Or use the branch you're working with
  pull_request:

jobs:
  build:
    runs-on: macos-latest  # Use macOS for iOS, Ubuntu for Android or cross-platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev @wdio/cli @wdio/appium-service appium allure-commandline

      - name: Set up Appium server
        run: |
          appium &  # Start Appium server in the background

      - name: Run WebDriverIO Tests
        run: |
          npm run android  # Runs android tests

      - name: Upload Allure Report as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
