name: Mobile Automation CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: macos-latest

    env:
      AVD_NAME: Pixel_4_API_30
      SYSTEM_IMAGE: system-images;android-30;google_apis;x86_64
      DEVICE_TYPE: pixel
      ANDROID_HOME: /Users/runner/Library/Android/sdk

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use specific version, not 'node'

      - name: Install Dependencies
        run: |
          npm install
          npm install --save-dev @wdio/cli @wdio/appium-service appium allure-commandline
          npm install -g appium

      - name: Run on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-window -no-audio -no-boot-anim
          disable-animations: true
          script: |
            echo "Waiting for emulator..."
            adb wait-for-device
            adb shell getprop sys.boot_completed

            echo "Starting Appium..."
            nohup appium > appium.log 2>&1 &
            sleep 10  # Give Appium time to fully start

            echo "Running tests..."
            npm run android -- --no-window

            echo "Generating Allure report..."
            npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
